### ISSUE TITLE
Add support for Samsung APKs

### ISSUE THREAD

**Issue by Emil007** [andi2022/wooper#3]
Since there are no more native apks provided for Pogo since a few versions, scanners had to switch to samsungs apk, which has a different package name (com.nianticlabs.pokemongo.ares), which of course kills wooper

**Comment by andi2022** [comment]
I will add support later this week.
On Thursday i have time to work on this.

**Comment by andi2022** [comment]
A short update.
I have now a early test version. I will now test a few hours the new version with google apk to see if i don't have bricked something. If this works well i can test the migration to the samsung apk that i have implemented and if also the other things working well.

**Comment by Emil007** [comment]
Thanks for the quick fix, i've been delaying the switch for a while because of time constraints but today i added "branch=samsung_apk" to the versions file and updated everything, however, either i'm stupid or i've found 2 issues:

1.) "ATV1: wooper.sh updated 1.4.0=>1.4.8 | Github branch samsung_apk, restarting script" worked, but it seems to have not updated the monitoring script, i now get the error "Something is not right! PoGo is not in focus. Killing PoGo and clearing junk." every 10 minutes

2.) while trying around i killed wooper on one device and had to reinstall it. It was installed with samsung_apk from the beginning:
`ATV1: wooper monitor updated 0 => 1.1.6 | Github branch samsung_apk`

However, after setup of apks and everything, i got this message:
`ATV1: Configured PoGo APK is google, a Samsung version is detected and will be uninstalled.`
Reboot fixed it

//EDIT: for some reason, after an hour of using samsung_apk on those two devices, i got this message:
`ATV5: Configured PoGo APK is google, a Samsung version is detected and will be uninstalled.
ATV8: Configured PoGo APK is google, a Samsung version is detected and will be uninstalled.
ATV5: New pogo version detected, =>0.327.0
ATV8: New pogo version detected, =>0.327.0`

**Comment by andi2022** [comment]
hi
thanks for testing. sorry i was too busy. i go now to vacation but i will do some more troubleshooting. i will push a new version that should fix some of the issues.

**Comment by andi2022** [comment]
new version is merged to samsung_apk branch. but not everything is fixed. not enough time on the airport. will do in the next few days a new try.

**Comment by Emil007** [comment]
Thanks for your great work, delay is no problem, take your time, you're doing this for free after all ;)

updating right now, will report back after testing it for a while. Old version was "updating pogo" on random atvs every few hours for the last week(s)

//EDIT: Sorry, i'm stupid, the update is pulled from GH and was 2 days ago:
` — 02.09.2024 21:28 ATV1: wooper monitor updated 1.1.6 => 1.1.14 | Github branch samsung_apk
`

didn't seem to have changed anything unfortunately, this is from today:

```
12:59 ATV8: Configured PoGo APK is google, a Samsung version is detected and will be uninstalled.
12:59 ATV9: Something is not right! PoGo is not in focus. Killing PoGo and clearing junk.
12:59 ATV8: New pogo version detected, =>0.327.0
13:00 ATV7: Something is not right! PoGo is not in focus. Killing PoGo and clearing junk.
13:00 ATV8: Start updating pogo
13:00 ATV8: PoGo 0.327.0, launcher started
13:00 ATV8: wooper monitor restarted after PoGo update
13:01 ATV3: Something is not right! PoGo is not in focus. Killing PoGo and clearing junk.
```

**Comment by andi2022** [comment]
i have now fixed the last part.
script should have the version 1.4.26 and monitor 1.1.19. when you change to the samsung_apk branch, edit the versions file and add apk=samsung. When you revert to a google pogo apk then change the value apk=google or remove it from the versions file.
i will update the Readme soon. I do now switch to the samsung apk and run it for a few hours. if it's working then i will merge the changes to develop and main branch.

**Comment by andi2022** [comment]
for the last 2 hours it runs smoothly. I go now to sleep and if tomorrow everything is fine i will merge the update with the main branch and make the announcment for the new release. a new gc build should arrive soon to support the new protos.
it's already merged to develop.

**Comment by Emil007** [comment]
Thanks, looks good for now, no notifications at all

Had problems updating to PIF 17.4 with it (but not pogo and gc) but that's probably something else, will look into that tomorrow - monitoring seems to work like a charm again, or at least nothing is erroring steadily anymore..
Thanks again =)

**Comment by andi2022** [comment]
It's merged with the main branch. Please switch back, i will delete soon the samsung_apk branch.
I had also some issue with PIF17.4, i will later loock at it.
